CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (
        role IN ('SUPPORT_ENGINEER', 'DEVELOPER')
    )
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    application_name VARCHAR(50) NOT NULL,
    environment VARCHAR(20) NOT NULL,
    error_logs TEXT,
    status VARCHAR(30) NOT NULL,
    created_by_id BIGINT NOT NULL,
    assigned_developer_id BIGINT,
    final_category VARCHAR(50),
    final_priority VARCHAR(20),
    actual_root_cause TEXT,
    actual_resolution TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT pk_incidents PRIMARY KEY (id),
    CONSTRAINT fk_incidents_created_by FOREIGN KEY (created_by_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_incidents_assigned_developer FOREIGN KEY (assigned_developer_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_incidents_application_name CHECK (
        application_name IN (
            'AUTH_SERVICE',
            'PAYMENT_SERVICE',
            'ORDER_SERVICE',
            'NOTIFICATION_SERVICE',
            'REPORTING_SERVICE'
        )
    ),
    CONSTRAINT ck_incidents_environment CHECK (
        environment IN ('DEV', 'QA', 'UAT', 'PROD')
    ),
    CONSTRAINT ck_incidents_status CHECK (
        status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')
    ),
    CONSTRAINT ck_incidents_final_category CHECK (
        final_category IS NULL OR final_category IN (
            'API',
            'DATABASE',
            'AUTHENTICATION',
            'DEPLOYMENT',
            'PERFORMANCE',
            'NETWORK',
            'INTEGRATION',
            'CONFIGURATION',
            'OTHER'
        )
    ),
    CONSTRAINT ck_incidents_final_priority CHECK (
        final_priority IS NULL OR final_priority IN (
            'LOW',
            'MEDIUM',
            'HIGH',
            'CRITICAL'
        )
    )
);

CREATE TABLE ai_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    incident_id BIGINT NOT NULL,
    suggested_category VARCHAR(50) NOT NULL,
    suggested_priority VARCHAR(20) NOT NULL,
    probable_root_cause TEXT NOT NULL,
    suggested_resolution TEXT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_analyses PRIMARY KEY (id),
    CONSTRAINT uq_ai_analyses_incident_id UNIQUE (incident_id),
    CONSTRAINT fk_ai_analyses_incident FOREIGN KEY (incident_id)
        REFERENCES incidents (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_analyses_suggested_category CHECK (
        suggested_category IN (
            'API',
            'DATABASE',
            'AUTHENTICATION',
            'DEPLOYMENT',
            'PERFORMANCE',
            'NETWORK',
            'INTEGRATION',
            'CONFIGURATION',
            'OTHER'
        )
    ),
    CONSTRAINT ck_ai_analyses_suggested_priority CHECK (
        suggested_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    )
);

CREATE INDEX idx_incidents_status
    ON incidents (status);

CREATE INDEX idx_incidents_created_by_id
    ON incidents (created_by_id);

CREATE INDEX idx_incidents_assigned_developer_id
    ON incidents (assigned_developer_id);

CREATE INDEX idx_incidents_created_at
    ON incidents (created_at);
